import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import {
  Connect,
  Header,
  Hero,
  Projects,
  Technologies,
  Resume,
  Contact,
} from "../components";
import { useRef } from "react";

export default function Home() {
  const headerRef = useRef();
  const heroRef = useRef();
  const projectsRef = useRef(null);
  const technologiesRef = useRef();
  const connectRef = useRef();
  const contactRef = useRef();

  const [currSection, setCurrSection] = useState(<Hero refProp={heroRef} />);

  const handleHeroClick = () => {
    // heroRef.current.scrollIntoView({ behavior: "smooth" });
    setCurrSection(<Hero refProp={heroRef} />);
  };

  const handleProjectsClick = () =>
    setCurrSection(<Projects refProp={projectsRef} />);

  const handleTechnologiesClick = () =>
    setCurrSection(<Technologies refProp={technologiesRef} />);

  const handleContactClick = () => setCurrSection(<Contact />);

  const handleResumeClick = () => setCurrSection(<Resume />);

  const handleConnectClick = () =>
    setCurrSection(<Connect refProp={connectRef} />);

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Jace Edwards Coding Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>

      <main>
        <Header
          refProp={headerRef}
          navHeroClick={handleHeroClick}
          navProjectsClick={handleProjectsClick}
          navTechnologiesClick={handleTechnologiesClick}
          navContactClick={handleContactClick}
          navResumeClick={handleResumeClick}
          navConnectClick={handleConnectClick}
        />
        {currSection}
      </main>
    </>
  );
}
