import Head from "next/head";
import styles from "../styles/Home.module.css";
import {
  Connect,
  Header,
  Hero,
  Projects,
  Technologies,
} from "../components/index";
import { useRef } from "react";

export default function Home() {
  const headerRef = useRef();
  const heroRef = useRef();
  const projectsRef = useRef(null);
  const technologiesRef = useRef();
  const connectRef = useRef();

  const handleHeroClick = () => {
    heroRef.current.scrollIntoView({ behavior: "smooth" });
  };

  const handleProjectsClick = () => {
    projectsRef.current.scrollIntoView({ behavior: "smooth" });
  };

  const handleTechnologiesClick = () => {
    technologiesRef.current.scrollIntoView({ behavior: "smooth" });
  };

  const handleConnectClick = () => {
    connectRef.current.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Jace Edwards Coding Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>

      <main>
        <Header
          refProp={headerRef}
          navHeroClick={handleHeroClick}
          navProjectsClick={handleProjectsClick}
          navTechnologiesClick={handleTechnologiesClick}
          navConnectClick={handleConnectClick}
        />
        <Hero refProp={heroRef} />
        <Projects refProp={projectsRef} />
        <Technologies refProp={technologiesRef} />
        <Connect refProp={connectRef} />
      </main>
    </>
  );
}
